name: "vio-assessment-solution-api"
services:
  vio-assessment-solution-mongo:
    container_name: 'vio-assessment-solution-mongo'
    image: mongo
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./.data/db:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DB: ${DB_NAME}

  vio-assessment-solution-api:
    container_name: 'vio-assessment-solution-api'
    env_file:
      - ./.env.prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - vio-assessment-solution-mongo
