name: "vio-assessment-solution"
services:
  vio-assessment-solution-mongo:
    container_name: 'vio-assessment-solution-mongo'
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./.data/db:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DB: ${DB_NAME}

  vio-assessment-solution-api:
    container_name: 'vio-assessment-solution-api'
    extends:
      file: ./vio-assessment-solution.api/docker-compose.dev.yaml
      service: vio-assessment-solution-api
    environment:
      PORT: ${PORT}
      UI_ORIGIN: ${UI_ORIGIN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      NODE_ENV: dev
      LOG_LEVEL: debug
      ENCRYPTION_KEY: vio-assessment-solution-encryption-key
      SSL: false
      API_VERSION: v1
      SESSION_SECRET: vio-assessment-solution-session-secret
      ACCESS_TOKEN_SECRET: vio-assessment-solution-access-token-secret
      REFRESH_TOKEN_SECRET: vio-assessment-solution-refresh-token-secret
      ACCESS_TOKEN_EXP_IN: 9000000 # 15min
    # depends_on:
    #   - vio-assessment-solution-mongo

  vio-assessment-solution-ui:
    container_name: 'vio-assessment-solution-ui'
    build:
      context: ./vio-assessment-solution.ui
      dockerfile: Dockerfile.dev
      args:
        VITE_REST_API_BASE_URL: ${UI_ENV_REST_API_BASE_URL}
        VITE_REST_API_ROOT_PATH: ${UI_ENV_REST_API_ROOT_PATH}
        VITE_REST_API_VERSION: ${UI_ENV_REST_API_VERSION}
        SERVE_PORT: ${UI_ENV_SERVE_PORT}
    ports:
      - ${UI_ENV_SERVE_PORT}:${UI_ENV_SERVE_PORT}
