FROM node:20.5.0-alpine AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install\
    && npm install -g tsc\
    && npm install -g serve

# Copy the rest of the application code to the container
COPY . .

ARG VITE_SERVE_PORT

# Build the application
RUN npm run build

EXPOSE $VITE_SERVE_PORT

CMD serve -s dist -l ${VITE_SERVE_PORT}
